### PR TITLE
fix: Added HomeFragment and AboutUsFragment

### LINKED ISSUE #13: Add Fragments for Home and About

### PR DESCRIPTION
**Pull request by somenath1435**
Fixes #13 

Changes: Added Fragments

### CODE REVIEW

File: app/src/main/java/com/example/saar/AboutUsFragment.java [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+                             Bundle savedInstanceState) {
+        // Inflate the layout for this fragment
+        return inflater.inflate(R.layout.fragment_about_us, container, false);
+    }
+
+    @Override
+    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
+        super.onViewCreated(view, savedInstanceState);
+        //you can set the title for your toolbar here for different fragments different titles
+        getActivity().setTitle("About Us");
```
Comment (atm1504) [inline app/src/main/java/com/example/saar/AboutUsFragment.java]: Don't hardcode strings

File: app/src/main/java/com/example/saar/MainActivity.java [hunk 2]
```diff
@@ -77,29 +81,40 @@ public boolean onOptionsItemSelected(MenuItem item) {
...
-        } else if (id == R.id.nav_about_us) {
-
-        } else if (id == R.id.nav_timeline) {
-
-        } else if (id == R.id.nav_team) {
 
-        } else if (id == R.id.nav_donate_now) {
-
-        } else if (id == R.id.nav_share) {
+        displaySelectedScreen(item.getItemId());
```
Comment (atm1504) [inline app/src/main/java/com/example/saar/MainActivity.java]: Comment out the use of this function

**Comment by somenath1435** [comment]
@atm1504 PR is updated
